apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
    - accounts-dev.auraenterprise.solutions
    - admin-accounts-dev.auraenterprise.solutions
  gateways:
    - istio-ingress/public-gateway
  http:
    - route:
        - destination:
            host: keycloak.apps-dev.svc.cluster.local
            port:
              number: 8080
