apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-spicedb
  namespace: apps-prod
spec:
  bootstrap:
    initdb:
      database: spicedb
      owner: spicedb
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0
  instances: 2
  monitoring:
    enablePodMonitor: true
  podMetadata:
    annotations:
      sidecar.istio.io/inject: "false"
  postgresql:
    parameters:
      shared_buffers: 128MB
      track_commit_timestamp: "on"
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
