apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: report-ms-secrets
spec:
  vaultAuthRef: report-ms
  mount: aura
  type: kv-v2
  path: prod/report-ms
  destination:
    name: report-ms-secrets
    create: true
  refreshAfter: 60s
  rolloutRestartTargets:
    - kind: Deployment
      name: report-ms
