apiVersion: v1
kind: ServiceAccount
metadata:
  name: report-ms
  namespace: apps-dev
---
apiVersion: v1
data:
  AURA_EMAIL_FROM_ADDRESS: kevinliusingapore@gmail.com
  AWS_REGION: ap-southeast-1
  AWS_S3_BUCKET_NAME: aura-ap-southeast-dev
  JWK_SET_URI: https://accounts-dev.auraenterprise.solutions/realms/aura/protocol/openid-connect/certs
  KEYCLOAK_CLIENT_ID: aura-application-client
  KEYCLOAK_CLIENT_REALM: aura
  KEYCLOAK_CLIENT_SERVER_URL: https://accounts-dev.auraenterprise.solutions
  MAIL_USERNAME: kevinliusingapore@gmail.com
  SPICEDB_PLAINTEXT: "true"
  SPICEDB_TARGET: spicedb:50051
  SPRING_PROFILES_ACTIVE: cloud
kind: ConfigMap
metadata:
  name: report-ms-config
  namespace: apps-dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: report-ms
  name: report-ms
  namespace: apps-dev
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: report-ms
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: report-ms
  name: report-ms
  namespace: apps-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-ms
  template:
    metadata:
      labels:
        app: report-ms
    spec:
      containers:
        - env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-aura-app
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-aura-app
            - name: DB_URL
              value: jdbc:postgresql://postgres-aura-rw:5432/aura
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=50
          envFrom:
            - configMapRef:
                name: report-ms-config
            - secretRef:
                name: report-ms-secrets
          image: 696085047789.dkr.ecr.ap-southeast-1.amazonaws.com/aura:report-ms
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 5
          name: report-ms
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "4"
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
          startupProbe:
            failureThreshold: 40
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 3
      imagePullSecrets:
        - name: ecr-pull
      initContainers:
        - env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-aura-app
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-aura-app
            - name: DB_URL
              value: jdbc:postgresql://postgres-aura-rw:5432/aura
            - name: SPRING_PROFILES_ACTIVE
              value: migration
          image: 696085047789.dkr.ecr.ap-southeast-1.amazonaws.com/aura:database-runner
          imagePullPolicy: Always
          name: db-migrator
          resources:
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 300Mi
      serviceAccountName: report-ms
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: report-ms
  namespace: apps-dev
spec:
  gateways:
    - istio-ingress/public-gateway
  hosts:
    - api-dev.auraenterprise.solutions
  http:
    - route:
        - destination:
            host: report-ms.apps-dev.svc.cluster.local
            port:
              number: 8080
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: report-ms
  namespace: apps-dev
spec:
  kubernetes:
    audiences:
      - vault
    role: report-ms-dev
    serviceAccount: report-ms
  method: kubernetes
  mount: kubernetes
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: report-ms-secrets
  namespace: apps-dev
spec:
  destination:
    create: true
    name: report-ms-secrets
  mount: aura
  path: dev/report-ms
  refreshAfter: 60s
  rolloutRestartTargets:
    - kind: Deployment
      name: report-ms
  type: kv-v2
  vaultAuthRef: report-ms
