apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
    - accounts.lab.lan
    - admin-accounts.lab.lan
  gateways:
    - istio-ingress/public-gateway
  http:
    - route:
        - destination:
            host: keycloak.apps-prod.svc.cluster.local
            port:
              number: 8080
