apiVersion: v1
kind: Namespace
metadata:
  name: apps-dev
  labels:
    env: dev
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-staging
  labels:
    env: staging
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-prod
  labels:
    env: prod
    istio-injection: enabled
