apiVersion: v1
kind: ServiceAccount
metadata:
  # VSO presents this SA's JWT to Vault's kubernetes auth method to obtain
  # a token for the `spicedb-<env>` role. Not the same SA as the SpiceDB
  # pods themselves — those are created by the operator.
  name: spicedb
