apiVersion: v1
kind: Service
metadata:
  name: aura-report-website
  labels:
    app: aura-report-website
spec:
  type: ClusterIP
  selector:
    app: aura-report-website
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
