apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-keycloak
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak

  postgresql:
    parameters:
      shared_buffers: "128MB"

  podMetadata:
    annotations:
      sidecar.istio.io/inject: "false"

  monitoring:
    enablePodMonitor: true

  storage:
    size: 1Gi   # overridden per env
