apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - virtualservice.yaml
  - vaultauth.yaml
  - vaultstaticsecret.yaml
namespace: apps-prod

patches:
  - target:
      kind: ConfigMap
      name: bff-config
    patch: |
      - op: add
        path: /data/NEXTAUTH_URL
        value: "https://app.auraenterprise.solutions"
      - op: add
        path: /data/KEYCLOAK_ISSUER
        value: "https://accounts.auraenterprise.solutions/realms/aura"
      - op: add
        path: /data/NEXT_PUBLIC_REPORT_SERVICE_URL
        value: "https://api.auraenterprise.solutions"
  - target:
      kind: Deployment
      name: aura-report-website
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
# TODO: bump replicas + tighten resource limits once we have actual prod load shape.
