apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bff-secrets
spec:
  vaultAuthRef: aura-report-website
  mount: aura
  type: kv-v2
  path: prod/bff
  destination:
    name: bff-secrets
    create: true
  refreshAfter: 60s
  rolloutRestartTargets:
    - kind: Deployment
      name: aura-report-website
