apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: aura-report-website
spec:
  hosts:
    - app.lab.lan
  gateways:
    - istio-ingress/public-gateway
  http:
    - route:
        - destination:
            host: aura-report-website.apps-prod.svc.cluster.local
            port:
              number: 3000
